# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1b6cbd8ca25aeed3429ede3631985b7"
name = "rainbows&dreams-wholesale-app"
handle = "rainbows-dreams-wholesale-app"
application_url = "https://apparatus-thanks-varied-impose.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = ["https://apparatus-thanks-varied-impose.trycloudflare.com/auth/callback", "https://apparatus-thanks-varied-impose.trycloudflare.com/auth/shopify/callback", "https://apparatus-thanks-varied-impose.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
