name = "wholesale-pricing"
type = "function"
api_version = "2023-07"

[build]
command = "echo 'Skipping build - javy deprecated'"
path = "dist/index.wasm"

[function]
type = "order_discounts"

[input.variables]
namespace = "wholesale"
key = "pricing_config"
